server:
  port: 8003
mybatis:
  type-aliases-package: com.aiden.springcloud.pojo
  configuration:
    cache-enabled: true
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DB03?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
#eureka配置,服务注册地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    #eureka 上面默认的描述信息
    instance-id: springcloud-provider-dept-8003

info:
  app.name: aiden-springcloud
  company.name: aiden.com


