server:
  port: 9527

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: getway9527.com
    prefer-ip-address: true

spring:
  application:
    name: springcloud-getway
  # ?? Gateway ??????????
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # ???????????????????????????"
          lower-case-service-id: true
      routes: # ??????
        - id: user-service # ??id???????????
          # uri: http://127.0.0.1:8081 # ??????? http??????
          uri: lb://springcloud-provider-dept # ??????? lb??????????????
          predicates: # ???????????????????????
            - Path=/dept/**
